

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/parking-space?createDatabaseIfNotExist=true
    username: root
    password: Root



#spring:
##  jpa:
##    hibernate:
##      ddl-auto: update
##  datasource:
##    url: jdbc:postgresql://localhost:5432/parking-space?createDatabaseIfNotExist=true
##    username: postgres
##    password: root

#spring:
#  jpa:
#    database: POSTGRESQL
#    show-sql: true
#  datasource:
#    platform: postgres
#    url: jdbc:postgresql://localhost:5432/parking-space?createDatabaseIfNotExist=true
#    username: postgres
#    password: root
#    hikari: public
#    driverClassName: org.postgresql.Driver
